# Generated by Django 6.0.1 on 2026-02-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
